language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: juniorhamish-github
    token:
      secure: I1F3JaN+1Dqpd0beUqXm4UxdzT1ncOsYK6pQU1MrHePyzSN3X/HI8ForC29ZrWkwkigB1WlstNpL9NFRe7IRgRSpIbFliOQ5IG8OQJw4msclMD4/K0/jrAxnPR37dLqchDkbJhQ4VuFwZ31/Fhyb/FOWEPV2wTgmy7iRA7bk3dG1YOM0zUgvZyrt9JP0fBmNzHLv9dLPSNH/d78GVIJP7LMxr3KFXU0VvMB26DBomRs7NFegcXTnL8P0q4TFdlSIO/fJ+vW07WCkBwZDnxnF5TDP4YTAm+9qA6pGYc4ENXK1v7Ba4//XBVnLWE+3GcL3AhIE8u3ClOG4QhOLGBy9pAxfJ1MYZCHoV8998A31TvMxe5g29zOPuaYAK1rKXdkywrJgPdea/t1mAt3TF0YLigYfs88K1RPtMLuUAszz+NLvYYch88dZtWbFg94MFBLwyInBolrW2vZ7J9EDqtb42rUS0yfVNzsH0dgI1IwNOVtNMUumGQOF4WZ8FtCieddIyXUTlHqRdprmk2b1njywGnXgcS+GYFYaDvOYPajZc2O8hFp6yz/f4nEMG6xkZ27LfehzVie6pLej4nwwp4tvTAs/hEOu9P4c9//rM1pSxNmv4qOExcx8ZQheDJUWsIPfzoAVL8KWaw9XFnE17BZp/kZhMKG+qa1FP9bKDw52Ndo=
jdk:
- oraclejdk8
script:
- ./gradlew sonarqube pitest
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle
