security:
  oauth2:
    client:
      clientId: 304386753342943
      clientSecret: cad70bac4cdd59d2e6f7b31c5f9baa63
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
