server:
  port: 8280
security:
  oauth2:
    client:
      client-id: my-app
      client-secret: my-app-secret
      access-token-uri: http://localhost:8180/oauth/token
      user-authorization-uri: http://localhost:8180/oauth/authorize
    resource:
      user-info-uri: http://localhost:8180/me